---
# ssh role

- name: LOCAL blank temp file
  copy:
    content: ""
    dest: /tmp/ansible-lines-test
    force: yes

- name: REMOTE blank temp file
  local_action: copy content="" dest="/tmp/ansible-lines-test" force="yes"


- name: Write users to temp REMOTE file
  lineinfile:
    path: "/tmp/ansible-lines-test"
    line: "{{ item.key }}"
  with_items: "{{ssh_users}}"

# fails to lookup
- name: Write users to LOCAL temp file
  local_action: lineinfile path="/tmp/ansible-lines-test" line="{{ item.key }}"
  with_items: "{{ssh_users}}"

